### ISSUE TITLE
Complete language support for all 95%+ languages

### ISSUE THREAD

**Issue by davelab6** [googlefonts/comfortaa#11]
I'd like to request just a few languages which have over 90% character support and are just missing a few characters :)

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Italian (it) | 108/108 | 100 |  |
| Slovenian (sl) | 112/112 | 100 |  |
| Ukrainian (uk) | 98/98 | 100 |  |
| Estonian (et) | 105/105 | 100 |  |
| Swahili (sw) | 39/39 | 100 |  |
| English (en) | 120/121 | 99 | \u2010 (‐) |
| German (de) | 125/126 | 99 | \u2010 (‐) |
| English (United Kingdom) (en-GB) | 120/121 | 99 | \u2010 (‐) |
| Spanish (es) | 129/130 | 99 | \u2010 (‐) |
| Spanish (Latin America) (es-419) | 129/130 | 99 | \u2010 (‐) |
| Dutch (nl) | 109/110 | 99 | \u2010 (‐) |
| Polish (pl) | 125/126 | 99 | \u2010 (‐) |
| Portuguese (pt) | 123/124 | 99 | \u2010 (‐) |
| Turkish (tr) | 129/130 | 99 | \u2010 (‐) |
| Catalan (ca) | 128/129 | 99 | \u2010 (‐) |
| Czech (cs) | 129/130 | 99 | \u2010 (‐) |
| Danish (da) | 109/110 | 99 | \u2010 (‐) |
| Lithuanian (lt) | 105/106 | 99 | \u2010 (‐) |
| Latvian (lv) | 108/109 | 99 | \u2010 (‐) |
| Norwegian (no) | 104/105 | 99 | \u01ce (ǎ) |
| Portuguese (Portugal) (pt-PT) | 123/124 | 99 | \u2010 (‐) |
| Romanian (ro) | 101/102 | 99 | \u2010 (‐) |
| Slovak (sk) | 130/131 | 99 | \u2010 (‐) |
| Swedish (sv) | 108/109 | 99 | \u2010 (‐) |
| Vietnamese (vi) | 156/157 | 99 | \u2010 (‐) |
| Afrikaans (af) | 107/108 | 99 | \u2010 (‐) |
| Icelandic (is) | 102/103 | 99 | \u2010 (‐) |
| Kazakh (kk) | 114/115 | 99 | \u2010 (‐) |
| French (fr) | 111/113 | 98 | \u2010 (‐), \u01d4 (ǔ) |
| Russian (ru) | 95/96 | 98 | \u2010 (‐) |
| Bulgarian (bg) | 91/92 | 98 | \u2010 (‐) |
| Filipino (fil) | 96/97 | 98 | \u2010 (‐) |
| Croatian (hr) | 88/89 | 98 | \u2010 (‐) |
| Indonesian (id) | 73/74 | 98 | \u2010 (‐) |
| Serbian (sr) | 90/91 | 98 | \u2010 (‐) |
| Azerbaijani (az) | 96/97 | 98 | \u2010 (‐) |
| Macedonian (mk) | 84/85 | 98 | \u2010 (‐) |
| Malay (ms) | 82/83 | 98 | \u2010 (‐) |
| Albanian (sq) | 86/87 | 98 | \u2010 (‐) |
| Kyrgyz (ky) | 101/103 | 98 | \u2010 (‐), \u04ca (ӊ) |
| Serbian (Latin) (sr-Latn) | 83/84 | 98 | \u2010 (‐) |
| Uzbek (uz) | 86/87 | 98 | \u2010 (‐) |
| Hungarian (hu) | 130/133 | 97 | \u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩) |
| Mongolian (mn) | 68/70 | 97 | \u2010 (‐), \u04ca (ӊ) |
| Finnish (fi) | 156/162 | 96 | \u2010 (‐), \u021f (ȟ), \u0292 (ʒ), \u01e5 (ǥ), \u01e9 (ǩ), \u01ef (ǯ) |

**Comment by alexeiva** [comment]
First I would like to check this against GF Latin Plus list which _should_ support all these languages.

Don't forget to remove `\u04ca (ӊ)` from `Kyrgyz` and `Mongolian (mn)`

Interesting why math symbols `\u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩)` are required for Hungarian:
* \u2052 (⁒) — _"used in Finno-Ugric Phonetic Alphabet to indicate a related borrowed form with different sound."_ I think this is a good-to-have glyph, but shouldn't be a requirement in GF Latin Plus.

* ⟨ , ⟩ — I have no idea how they are used in Hungarian. Need more research.

In place of Finnish the correct language should be [Skolt Sami](https://en.wikipedia.org/wiki/Skolt_Sami_language) [glyphs \u0292 (ʒ), \u01e5 (ǥ), \u01e9 (ǩ), \u01ef (ǯ)], and [Finnish Romany](https://en.wikipedia.org/wiki/Finnish_Kale) [glyph \u021f (ȟ)] 

I think we should globally add these symbols to GF Latin Plus for compatibility with CLDR:
`\u01ce (ǎ) \u2010 (‐), \u01d4 (ǔ)`

Or, possibly, `\u01ce (ǎ) \u01d4 (ǔ)` may be a CLDR bug, since [uniview](https://r12a.github.io) lists them as Pinyin diacritic-vowel combinations.

I doubt these are useful in Latin Plus:
`\u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩)`

Glyph `ʒ U+0292` can be made from a component of `ӡ u+04E1` featured in Cyrillic Pro. It is also an IPA glyphs this range wasn't meant to be part of Latin Plus.

<img width="774" alt="screen shot 2017-11-07 at 1 42 21 pm" src="https://user-images.githubusercontent.com/16634089/32486927-89b3f0ea-c3c1-11e7-8946-2c7d60ee1fe7.png">

**Comment by davelab6** [comment]
Agree `\u01ce (ǎ) \u2010 (‐), \u01d4 (ǔ)` should be added to Plus

I think `\u2052 (⁒), \u27e8 (⟨), \u27e9 (⟩)` should be added to Plus, as they are simple to draw.

Suggested drawing order and parent/component-child relationships (which glyphs to make from components) would be great to document in the GF Encodings README
